### ISSUE TITLE
How update to  Chromium version 79.0.3945.1

### ISSUE THREAD

**Issue by ieclipser** [equoplatform/chromium-swt#101]
Hello：
       The plugin is working with the version 59 of Chromium(CEF 3.3071)，
       too old version for me， I want to use the newer version.
       How to update to Chromium version 79.0.3945.1
       https://github.com/chromiumembedded/cef

      Would you give me some tip ?  or  do you have any plan to update to new version Chromium ?
      
      Thanks.

**Comment by butzek** [comment]
Chromium 59 is over 2.5 years old - its really time for an update or at least a short description what to do on a manual update.

**Comment by gzunino** [comment]
@ieclipser @butzek if you need CEF updates take a look to "Equo Chromium Enterprise" here: https://www.equoplatform.com/#/pricing
