### ISSUE TITLE
How to install Flash Player into embeded chromium？

### ISSUE THREAD

**Issue by ieclipser** [equoplatform/chromium-swt#102]
Hello：
          when I visite the vedio web page， it shows the tip of  “Install Adobe Flash Player”， how to install flash player plugin into embeded chromium， so i can view the content of the vedio through the embeded chromium browser.
          Thanks!

**Comment by tomvdbussche** [comment]
Flash player has been deprecated for a while now and is nearing it's EOL (in 2021 I think). For videos you should use the `<video>` tag instead, which has been around for 7 years now and works natively in almost all browsers: https://caniuse.com/#feat=video

**Comment by gzunino** [comment]
Hi @ieclipser support for flash is offered as part of "Equo Chromium Enterprise" here: https://www.equoplatform.com/#/pricing
