### ISSUE TITLE
Windows 10 requires admin rights

### ISSUE THREAD

**Issue by tomvdbussche** [equoplatform/chromium-swt#108]
We have encountered some issues running the chromium browser in a Windows 10 environment. When running Eclipse as a regular user, AppLocker prevents the execution of the chromium executable because it is located in the users home directory (in an `.swt` folder). We can circumvent this by running Eclipse with admin right, but this is far from ideal.

**Comment by nedtwigg** [comment]
I don't think chromium.swt is doing anything differently than regular SWT.  FWIW, I am not seeing this behavior on my machine, though perhaps my plain IT setup (pretty much just Win 10 defaults) is more permissive than a typical corporate setup.

**Comment by gzunino** [comment]
Hi @tomvdbussche for customization and specific scenarios you can look at "Equo Chromium Enterprise" offering here: https://www.equoplatform.com/#/pricing
