### ISSUE TITLE
How to generate/ build swt-chromium-0102-win32.dll?

### ISSUE THREAD

**Issue by SrirekhaPK** [equoplatform/chromium-swt#115]
For using latest CEF version within chromium.swt,  need to update the swt-chromium-0102-win32.dll also. Could not found any docs regarding this. While building subprocess helper executable and native library, this dll is not generated. Could you please specify how to build this dll from source.

**Comment by AndrewMore1** [comment]
It's not present, you'll have to do your own implementation.

**Comment by SrirekhaPK** [comment]
Is the source code implementation is available for the existing version for reference?

**Comment by sarahkay10** [comment]
It will be useful to have some specifications or instructions for the implementation.

**Comment by gzunino** [comment]
Hi, for updated versions you can look at "Equo Chromium Enterprise" offering here: https://www.equoplatform.com/#/pricing
