### ISSUE TITLE
Can not take a snapshot of the Browser Widget

### ISSUE THREAD

**Issue by lcaron** [equoplatform/chromium-swt#118]
Environment : SWT 3.106.3 x86_64 on Windows 10

I try to take a snapshot of the widget by using the following code (that works fine for all SWT Control, including Browser) :

```
final GC gc = new GC(browser);
final Image image = new Image(Display.getCurrent(), browser.getSize().x, browser.getSize().y);
browser.addListener(SWT.Dispose, e -> {
	if (!image.isDisposed()) {
		image.dispose();
	}
});
gc.copyArea(image, 0, 0);
gc.dispose();
```

The resulting image is black (it seems that imageData is null)

**Comment by parnold-x** [comment]
@lcaron Did you find a workaround?

**Comment by lcaron** [comment]
Yes, I used Swing (like in https://www.baeldung.com/java-taking-screenshots)
