### ISSUE TITLE
how to build linux-arm64 version

### ISSUE THREAD

**Issue by wanglf589** [equoplatform/chromium-swt#120]
Can the chromium.libiary project build linux-arm64 version?
How to build linux-arm64 version of libswt-chromium-gtk-so library under the directory of chromium-3701
My mailbox: itru589@163.
![image](https://user-images.githubusercontent.com/45505649/109753509-5b255080-7c1d-11eb-96cd-65ca8cc2f942.png)
com[](url)

**Comment by lonelion** [comment]
Hi, 

For ARM support, specific features, newer versions of CEF, and more, please check out the "Equo Chromium Enterprise" offering here: https://www.equoplatform.com/#/pricing.
