### ISSUE TITLE
Mouse Events not working

### ISSUE THREAD

**Issue by dstainhauser** [equoplatform/chromium-swt#64]
When installing a mouse listener on a webview
```

chromium.addMouseListener(new MouseListener() {
                       @Override
			public void mouseUp(MouseEvent e) {
			}

			@Override
			public void mouseDown(MouseEvent e) {
			}

			@Override
			public void mouseDoubleClick(MouseEvent e) {
			}
		});

```
none of the mouse events are propagated with a mouse click.
Thanks for looking at this issue.

**Comment by gzunino** [comment]
CEF handles all mouse events and don't bubble up them. 
I don't see an easy way to implement this.

**Comment by jimmybirrias** [comment]
is there any new for this issue?
