### ISSUE TITLE
Keeping up with CEF updates

### ISSUE THREAD

**Issue by jrpajr** [equoplatform/chromium-swt#65]
Hello, 

today the plugin is working with the version 59 of Chromium(CEF 3.3071). 

I would like to know what are the plans to keep up with the CEF updates. 

Thanks.

**Comment by gzunino** [comment]
Hi @jrpajr , there are plans to update, but some funding will be ideal to allow allocating the resources to do it.

**Comment by riederm** [comment]
hey @jrpajr 
which exact version of CEF are you using? I tried several 3.3071 from http://opensource.spotify.com/cefbuilds/index.html (windows 64 bit) and I keep getting an error from link.exe: **"libcef.lib" cannot be accessed.**

**Comment by gzunino** [comment]
Hi @jrpajr if you need CEF updates take a look to "Equo Chromium Enterprise" here: https://www.equoplatform.com/#/pricing
