### ISSUE TITLE
Keyboard events (like ctrl-s for saving) is not working 

### ISSUE THREAD

**Issue by jcompagner** [equoplatform/chromium-swt#70]
As a drop in replacement of the standard Browser widget we bumb into that keyboard events like shortcuts (CTRL-S) are not coming into the eclipse environment
It seems that the default IE browser has some Ole intergration that sends those to eclipse to be able to handle them, see the stack below.
Is it possible to have something like this for chrome?
I will try to workaround this by adding a BrowserFunction that capture those keystokes..

Thread [main] (Suspended (breakpoint at line 283 in VisualFormEditor))	
	VisualFormEditor.doSave(IProgressMonitor) line: 283	
	SaveableHelper.lambda$0(ISaveablePart, IProgressMonitor) line: 157	
	1773620674.run(IProgressMonitor) line: not available	
	SaveableHelper.lambda$3(IRunnableWithProgress, boolean[], IProgressMonitor) line: 274	
	398744151.run(IProgressMonitor) line: not available	
	ModalContext.runInCurrentThread(IRunnableWithProgress, IProgressMonitor) line: 438	
	ModalContext.run(IRunnableWithProgress, boolean, IProgressMonitor, Display) line: 354	
	WorkbenchWindow.lambda$4(StatusLineManager, IRunnableWithProgress, boolean, InvocationTargetException[], InterruptedException[]) line: 2249	
	1511554260.run() line: not available	
	BusyIndicator.showWhile(Display, Runnable) line: 72	
	WorkbenchWindow.run(boolean, boolean, IRunnableWithProgress) line: 2247	
	SaveableHelper.runProgressMonitorOperation(String, IRunnableWithProgress, IRunnableContext, IShellProvider) line: 281	
	SaveableHelper.runProgressMonitorOperation(String, IRunnableWithProgress, IWorkbenchWindow) line: 262	
	SaveableHelper.savePart(ISaveablePart, IWorkbenchPart, IWorkbenchWindow, boolean) line: 161	
	WorkbenchPage.saveSaveable(ISaveablePart, IWorkbenchPart, boolean, boolean) line: 3976	
	WorkbenchPage.saveEditor(IEditorPart, boolean) line: 3990	
	SaveHandler.execute(ExecutionEvent) line: 57	
	HandlerProxy.execute(ExecutionEvent) line: 294	
	E4HandlerProxy.execute(IEclipseContext, Map, Event, IEvaluationContext) line: 96	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: not available	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: not available	
	Method.invoke(Object, Object...) line: not available	
	MethodRequestor.execute() line: 58	
	InjectorImpl.invokeUsingClass(Object, Class<?>, Class<Annotation>, Object, PrimaryObjectSupplier, PrimaryObjectSupplier, boolean, boolean, boolean) line: 320	
	InjectorImpl.invoke(Object, Class<Annotation>, Object, PrimaryObjectSupplier, PrimaryObjectSupplier) line: 254	
	ContextInjectionFactory.invoke(Object, Class<Annotation>, IEclipseContext, IEclipseContext, Object) line: 173	
	WorkbenchHandlerServiceHandler(HandlerServiceHandler).execute(ExecutionEvent) line: 156	
	Command.executeWithChecks(ExecutionEvent) line: 497	
	ParameterizedCommand.executeWithChecks(Object, Object) line: 490	
	HandlerServiceImpl.executeHandler(ParameterizedCommand, IEclipseContext) line: 213	
	KeyBindingDispatcher.executeCommand(ParameterizedCommand, Event) line: 308	
	KeyBindingDispatcher.press(List<KeyStroke>, Event) line: 584	
	KeyBindingDispatcher.processKeyEvent(List<KeyStroke>, Event) line: 653	
	KeyBindingDispatcher.filterKeySequenceBindings(Event) line: 443	
	KeyBindingDispatcher.access$2(KeyBindingDispatcher, Event) line: 386	
	KeyBindingDispatcher$KeyDownFilter.handleEvent(Event) line: 96	
	EventTable.sendEvent(Event) line: 89	
	Display.filterEvent(Event) line: 1194	
	WebSite(Widget).sendEvent(Event) line: 1054	
	WebSite(Widget).sendEvent(int, Event, boolean) line: 1079	
	WebSite(Widget).sendEvent(int, Event) line: 1064	
	WebSite(Widget).sendKeyEvent(int, int, long, long, Event) line: 1106	
	WebSite(Widget).sendKeyEvent(int, int, long, long) line: 1102	
	WebSite(Widget).wmChar(long, long, long) line: 1489	
	WebSite(Control).WM_CHAR(long, long) line: 4888	
	WebSite(Control).windowProc(long, int, long, long) line: 4768	
	Display.windowProc(long, long, long, long) line: 4778	
	OS.DispatchMessage(MSG) line: not available [native method]	
	OleFrame.getMsgProc(long, long, long) line: 276	
	OS.PeekMessage(MSG, long, int, int, int) line: not available [native method]	
	IE.handleDOMEvent(OleEvent) line: 1607	
	IE.lambda$4(OleEvent) line: 360	
	1753073638.handleEvent(OleEvent) line: not available	
	OleEventTable.sendEvent(OleEvent) line: 58	
	OleEventSink.notifyListener(int, OleEvent) line: 160	
	OleEventSink.Invoke(int, long, int, int, long, long, long, long) line: 128	
	OleEventSink.access$1(OleEventSink, int, long, int, int, long, long, long, long) line: 105	
	OleEventSink$1.method6(long[]) line: 79	
	COMObject.callback6(long[]) line: 122	
	COM.VtblCall(int, long, MSG) line: not available [native method]	
	IOleInPlaceActiveObject.TranslateAccelerator(MSG) line: 25	
	OleFrame.translateOleAccelerator(MSG) line: 821	
	OleFrame.getMsgProc(long, long, long) line: 226	
	OS.PeekMessage(MSG, long, int, int, int) line: not available [native method]	
	Display.readAndDispatch() line: 3542	
	PartRenderingEngine$5.run() line: 1173	
	Realm.runWithDefault(Realm, Runnable) line: 338	
	PartRenderingEngine.run(MApplicationElement, IEclipseContext) line: 1062	
	E4Workbench.createAndRunUI(MApplicationElement) line: 155	
	Workbench.lambda$3(Display, WorkbenchAdvisor, int[]) line: 644	
	636953520.run() line: not available	
	Realm.runWithDefault(Realm, Runnable) line: 338	
	Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 566	
	PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 150	
	IDEApplication.start(IApplicationContext) line: 155	
	EclipseAppHandle.run(Object) line: 203	
	EclipseAppLauncher.runApplication(Object) line: 137	
	EclipseAppLauncher.start(Object) line: 107	
	EclipseStarter.run(Object) line: 400	
	EclipseStarter.run(String[], Runnable) line: 255	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: not available	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: not available	
	Method.invoke(Object, Object...) line: not available	
	Main.invokeFramework(String[], URL[]) line: 661	
	Main.basicRun(String[]) line: 597	
	Main.run(String[]) line: 1476	
	Main.main(String[]) line: 1449

**Comment by PhaserEditor2D** [comment]
+1

**Comment by jcompagner** [comment]
we worked around it now by sending all the keystrokes from the the browser back to eclipse and then testing if there are Bindings/Commands for that enabled and execute them. This way the shortcuts work, but it is a bit tricky because we have to swallow all the keystrokes even if they maybe don't hit on a binding.

**Comment by PhaserEditor2D** [comment]
Hi @jcompagner

Please can you share the code with the workaroud? I am facing the same problem.

**Comment by jcompagner** [comment]
We are using websocket communication to talk back to the eclipse environment

so i have something like this in the browser:

```
$(document).keydown(function(objEvent) {
  $editorService.keyPressed(objEvent);
  return  false;
});
```

and then $editorService is a wrapper around a websocket protocol that sends that to eclipse as a json package
that package is picked up as:

```
		int keyCode = args.optInt("keyCode");
		boolean isCtrl = args.optBoolean("ctrl");
		boolean isShift = args.optBoolean("shift");

		IBindingService bindingService = editorPart.getSite().getService(IBindingService.class);
		int modifier = 0;
		if (isCtrl) modifier = SWT.CTRL;
		if (isShift) modifier = SWT.SHIFT | modifier;
		if (keyCode == 46 || keyCode == 8) keyCode = SWT.DEL;
		else if (keyCode == 115) keyCode = SWT.F4;
		Binding perfectMatch = bindingService.getPerfectMatch(KeySequence.getInstance(KeyStroke.getInstance(modifier, keyCode)));
		if (perfectMatch == null)
		{
			@SuppressWarnings("unchecked")
			Collection<Binding> partialMatches = bindingService.getConflictsFor(KeySequence.getInstance(KeyStroke.getInstance(modifier, keyCode)));
			if (partialMatches != null) for (Binding bid : partialMatches)
			{
				if (bid.getParameterizedCommand().getCommand().isEnabled())
				{
					perfectMatch = bid;
				}
			}
		}
		if (perfectMatch != null && perfectMatch.getParameterizedCommand().getCommand().isEnabled())
		{
			try
			{
				perfectMatch.getParameterizedCommand().executeWithChecks(null, null);
			}
			catch (Exception e)
			{
				ServoyLog.logError(e);
			}
		}

		return null;
```

**Comment by PhaserEditor2D** [comment]
Thanks! @jcompagner

**Comment by davidmedinasigasi** [comment]
+1

**Comment by riederm** [comment]
+1
