### ISSUE TITLE
Focus does not return to browser after SWT dialog or JS popup

### ISSUE THREAD

**Issue by Daan-** [equoplatform/chromium-swt#74]
When opening an SWT dialog or a Javascript dialog (see #34), after closing it the focus does not return to the browser window.

Expected behaviour
Key events are handled after focus lost/regained without the user clicking on the page.

**Steps to reproduce**
- Compile/run the attached sample java program
- Type keys a b c. The letter is shown in the page
- After 10 seconds an SWT dialog opens
- Close the dialog (click OK or Cancel). The main window regains focus
- Do not click on the browser window
- Type any key
- The key should show on the page but it does not because the event handler is not called
- Click in the browser window
- Event handling is restored

Sample program:
    public class SwtPopupDemo {
    
        public static void main(String[] args) {
            Display display = new Display();
            Shell shell = new Shell(display);
            shell.setLayout(new FillLayout(SWT.VERTICAL));
    
            Browser browser = new Browser(shell, SWT.NONE);
    
            // the key typed is shown on the page.
            // after 10 seconds, an SWT dialog opens
            // when the dialog is closed, the browser gets focus again, but the key handler does not get called until you click into the page.
            browser.setText("<html>" +
                    "<script>" +
                    "document.addEventListener('keyup',function(e){document.getElementById('p').innerHTML=e.key})" +
                    "</script>" +
                    "<body><p id='p'>X</p></body>" +
                    "</html>");
    
            shell.setSize(150, 150);
    
            shell.open();
    
            new Thread(() -> {
                try {
                    Thread.sleep(10000);
                    Display display1 = new Display();
                    Shell shell1 = new Shell(display1);
                    shell1.setLayout(new FillLayout(SWT.VERTICAL));
    
                    ColorDialog dialog = new ColorDialog(shell1);
                    dialog.open();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }).start();
    
            while (!shell.isDisposed()) {
                if (!display.readAndDispatch()) {
                    display.sleep();
                }
            }
            display.dispose();
        }
    }

build.gradle:

    dependencies {
        testCompile group: 'junit', name: 'junit', version: '4.12'
        compile group: 'org.eclipse', name: 'org.eclipse.swt.chromium', version: '0.9.1.201904260302'
        compile group: 'org.eclipse', name: 'org.eclipse.swt.chromium.win32.win32.x86_64', version: '0.9.1.201904260302'
        compile (group: 'org.eclipse.platform', name: 'org.eclipse.swt.win32.win32.x86_64', version: '3.106.3') {
            exclude group: 'org.eclipse.platform', module: 'org.eclipse.swt'
        }
        implementation 'com.github.jnr:jnr-ffi:2.1.9'
        implementation 'com.github.jnr:jffi:1.2.18'
        implementation 'com.github.jnr:jnr-x86asm:1.0.2.v201505052040'
        implementation 'org.ow2.asm:asm:7.1'
        implementation 'org.ow2.asm:asm-util:7.1'
        implementation 'org.ow2.asm:asm-tree:7.1'
        implementation 'org.ow2.asm:asm-analysis:7.1'
        implementation 'org.ow2.asm:asm-commons:7.1'
    }

This is also related to #34 , as that issue can also still be reproduced

**Comment by gzunino** [comment]
This seems to be Windows only

**Comment by Daan-** [comment]
That is possible yes, I didn't test on other platforms...
