### ISSUE TITLE
Filckering issue in chromium browser resize

### ISSUE THREAD

**Issue by V-Dev144** [equoplatform/chromium-swt#83]
Whenever I resize the chromium browser in eclipse photon RCP editor, there is a black color flickering appears. And also when I close the editor, black screen appears.

**Comment by gzunino** [comment]
Hi @V-Dev144  which OS ?

**Comment by V-Dev144** [comment]
Windows 10 64 bit

**Comment by davidmedinasigasi** [comment]
I'm also having this issue on Win 10 :(

**Comment by MichaelFroeschen** [comment]
Still an issue

**Comment by MichaelFroeschen** [comment]
On Linux this is no real issue, since the black color is only visible in the areas that are redrawn.
On Windows the flickering affects the whole browser instance

**Comment by riederm** [comment]
Same issue here, are there any ideas where the problem is?
