### ISSUE TITLE
chromium-swt/rls/repository & chromium-cef/rls/repository return an AccessDenied

### ISSUE THREAD

**Issue by hmarchadour** [equoplatform/chromium-swt#88]
Hi,
I've try several way to get latest repositories but it seems to be down or unavailable.
There is perhaps something to do with the equo-chromium-swt.ams3.digitaloceanspaces.com ?

With a browser:
https://equo-chromium-cef.ams3.digitaloceanspaces.com/rls/repository
![cap 24](https://user-images.githubusercontent.com/1506357/64410293-038b4080-d08b-11e9-8dfc-5d86d03b6fa9.png)
https://equo-chromium-swt.ams3.digitaloceanspaces.com/rls/repository
![cap 25](https://user-images.githubusercontent.com/1506357/64410295-05ed9a80-d08b-11e9-9f70-2d68d1519079.png)

With p2 browser or eclipse:
![cap 26](https://user-images.githubusercontent.com/1506357/64410303-0ab24e80-d08b-11e9-8371-7ee3a5113d9d.png)

With wget:
`wget --recursive --no-parent https://equo-chromium-swt.ams3.digitaloceanspaces.com/rls/repository --user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"`

`
--2019-09-05 17:27:31--  https://equo-chromium-swt.ams3.digitaloceanspaces.com/rls/repository
Résolution de equo-chromium-swt.ams3.digitaloceanspaces.com (equo-chromium-swt.ams3.digitaloceanspaces.com)… 5.101.110.225
...
 403 Forbidden`

**Comment by hmarchadour** [comment]
I'm alone with this issue?

As workaround, I've build the update site locally.
It works fine for the **org.eclipse.swt.chromium.repository**.
In another hand, build chromium-cef repository seems difficult.

I've followed the https://github.com/maketechnology/chromium.swt/tree/master/chromium-library Readme but I don't understand the "Copy library and binary from target/release/ to corresponding eclipse fragment" step (and the fragment location...). In my old cef-rls-0.7, I've a "com.make.chromium.cef.feature" but it does not figure on the git repository.

Thanks for looking at this issue.

**Comment by gzunino** [comment]
I don't see any problem accessing those repos:
![image](https://user-images.githubusercontent.com/2495175/65165985-38e24780-da16-11e9-90f1-f8982adc7a95.png)

![image](https://user-images.githubusercontent.com/2495175/65166223-aee6ae80-da16-11e9-8707-66088b2bcb5c.png)

**Comment by hmarchadour** [comment]
Thanks for your response.
In deed, it seems to depend on the "reader". It's not a "p2" repository ?
I try to mirror this update site without success... There is a way to download it as an archive ?

**Comment by gzunino** [comment]
It is a P2 repository: https://dl.maketechnology.io/chromium-swt/rls/repository/p2.index
It can be browsed with oomph Repository Explorer View for example and used in tycho builds, or installed in eclipse, etc.
How are you trying to mirror? Can you put a command or minimal example to reproduce the issue? Maybe there is some kind of problem while mirroring.

**Comment by hmarchadour** [comment]
When I use it directly as an update site in a .target 

`!MESSAGE Unexpected error loading extension: org.eclipse.equinox.p2.updatesite.metadataRepository
!STACK 0
java.lang.ClassCastException: org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager cannot be cast to org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager
	at org.eclipse.equinox.internal.p2.metadata.repository.LocalMetadataRepository.setProperty(LocalMetadataRepository.java:325)
!STACK 0
java.lang.ClassCastException: org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager cannot be cast to org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager
	at org.eclipse.equinox.internal.p2.metadata.repository.LocalMetadataRepository.setProperty(LocalMetadataRepository.java:325)
	at org.eclipse.equinox.p2.repository.spi.AbstractRepository.setProperty(AbstractRepository.java:189)
`
...
`
[ERROR] Failed to resolve target definition /home/integration/slave_jenkins/workspace/SmartEA-Gerrit@2/product/core/./releng/fr.obeo.smartea.core.target/SmartEA-Core.target: Failed to load p2 metadata repository from location http://dl.maketechnology.io/chromium-swt/rls/repository: Unable to read repository at http://dl.maketechnology.io/chromium-swt/rls/repository/content.xml. hostname in certificate didn't match: <dl.maketechnology.io> != <firebaseapp.com> OR <firebaseapp.com> OR <*.firebaseapp.com> -> [Help 1]
`

**Comment by hmarchadour** [comment]
To mirror the update site, I use 
`./eclipse -nosplash –verbose -application org.eclipse.equinox.p2.metadata.repository.mirrorApplication -source https://equo-chromium-swt.ams3.digitaloceanspaces.com/rls/repository -destination ./chromium-swt-rls`

The result : 
`
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1 (file:/***/Contents/Eclipse/plugins/org.eclipse.ecf.provider.filetransfer.httpclient4_1.1.200.v20170314-0133.jar) to method sun.security.ssl.SSLSocketImpl.setHost(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations`
And nothing in the ./chromium-swt-rls folder

**Comment by hmarchadour** [comment]
`./eclipse -nosplash –verbose -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication -source https://equo-chromium-swt.ams3.digitaloceanspaces.com/rls/repository -destination ./chromium-swt-rls`

The result : 

`
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1 (file:/***/Contents/Eclipse/plugins/org.eclipse.ecf.provider.filetransfer.httpclient4_1.1.200.v20170314-0133.jar) to method sun.security.ssl.SSLSocketImpl.setHost(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`
