### ISSUE TITLE
chromium.setText -> Refusing to load URL as it exceeds 2097152 characters.

### ISSUE THREAD

**Issue by dstainhauser** [equoplatform/chromium-swt#89]
When setting a long text on chromium with setText, we get the following error in the log

[0917/171035.151:WARNING:navigator_impl.cc(342)] Refusing to load URL as it exceeds 2097152 characters.

The browser then stays blank.

Obviously, the text is url encoded and then set as the url, which indeed has a certain limitation. The size limit depends on the number of escaped characters and is a bit shorter in practice as the 2 MB.

Why is the text set as the url? Is there another way to implement this, so we don't have a size restriction when setting a html text on chromium?

Thanks for help (not urgent).

**Comment by gzunino** [comment]
It was implemented in this way because it was much faster to load the page in this way  (the url can be send during the browser creation) than loading the source as text (need to wait for the browser creation, several events and then load the source). 
I think we can check the size and use the slower variation in case the size of the url is longer than the limit.
Thanks for the report.

**Comment by dstainhauser** [comment]
Hi Guillermo

Thanks for the immediate reply. Checking for the size as an alternate variation sounds like a good way to make it fast, but also stable.

We have a workaround for the time being, but adopting the implementation in the chromium plugin would be great for everybody.

BTW: Chromium is now ways faster without the debug logs and runs on macOS perfectly. Thanks for this release. 

Daniel

**Comment by aptmac** [comment]
Hi! I've been encountering this issue using swt-chromium as supplied by eclipse. I was wondering if there is any way around the character limitation, or if there's an alternate way to load a webpage with more than 2097152 characters.

The use case here is that JDK Mission Control is trying to use swt-chromium to display a (potentially) extremely large graph, and this is the error we're encountering at the moment. Any advice?

**Comment by gzunino** [comment]
Hi @aptmac. The alternative is to save the content to a temp file and load the url to the file. Even newer versions of cef remove the option to load html text directly, and you can only load a url with the the same char limit.
BTW, we do have newer versions of the widget based on updated chromium engine, and commercial support, check https://www.equoplatform.com/#/pricing.

**Comment by aptmac** [comment]
> Hi @aptmac. The alternative is to save the content to a temp file and load the url to the file. Even newer versions of cef remove the option to load html text directly, and you can only load a url with the the same char limit.

Ah that's unfortunate, but thank you for the reply.

> BTW, we do have newer versions of the widget based on updated chromium engine, and commercial support, check https://www.equoplatform.com/#/pricing.

We consume chromium-swt through Eclipse and Platform SWT itself so that's where we'd be needing a fix for this if it were possible.
