### ISSUE TITLE
Status and progress of this project

### ISSUE THREAD

**Issue by col-panic** [equoplatform/chromium-swt#92]
Hy there!

Is there any source/outlet concerning the planned further work on this project? 

The latest info on releases seems to come from https://bugs.eclipse.org/bugs/show_bug.cgi?id=405031

**Comment by PyvesB** [comment]
You can also check out the linked bug which tracks the actual contribution, [Bug 549585](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549585).

**Comment by gzunino** [comment]
Hi @col-panic for comercial support and CEF updates take a look to "Equo Chromium Enterprise" here: https://www.equoplatform.com/#/pricing
