### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by wjtraast** [equoplatform/chromium-swt#93]
An error occurred during the build proces while running unittests.

See attached error log.

[hs_err_pid17340.log](https://github.com/maketechnology/chromium.swt/files/3793413/hs_err_pid17340.log)

**Comment by cplacotas** [comment]
I have the same issue. 
Failing at org.eclipse.swt.internal.chromium.ChromiumLib.cefswt_init
I am using Windows 10.
