### ISSUE TITLE
UnsatisfiedLinkError on RHEL7 due to Chromiums GLIBC_2.18 version requirement

### ISSUE THREAD

**Issue by jacobfilik** [equoplatform/chromium-swt#94]
Making a test view in an eclipse RCP application running on RHEL7 throws:

java.lang.UnsatisfiedLinkError: /home/test/.swt/lib/linux/x86_64/chromium-3071/libchromium_swt_0102.so: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/test/.swt/lib/linux/x86_64/chromium-3071/libchromium_swt_0102.so)

I think this is a known issue in chromium that was fixed [here.](https://bugs.chromium.org/p/chromium/issues/detail?id=749077)

**Comment by gzunino** [comment]
Hi @jacobfilik For support in old operating systems take a look to "Equo Chromium Enterprise" here: https://www.equoplatform.com/#/pricing
