### ISSUE TITLE
How can I add an downloadhandler?

### ISSUE THREAD

**Issue by mifritscher** [equoplatform/chromium-swt#95]
I found something about a downloadhandler cef_client_t, but could not find a way to give the browser one - or create a downloadhandler...

Any hints?

**Comment by gzunino** [comment]
Chromium Browser should present a download dialog as it does the standard
SWT Browser, if not then there is a bug.

--
Guillermo Zunino
guillez@gmail.com

**Comment by mifritscher** [comment]
Sadly, there was no reaction at all. I'll try to make a little demo site.

**Comment by mifritscher** [comment]
If I read the documentation correctly, the download is blocked altogether if there is no download handler registered. This happens in my case.

Example code with a link to a example site:
```
package test;

import org.eclipse.swt.SWT;
// import org.eclipse.swt.browser.Browser;
import org.eclipse.swt.chromium.Browser;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class Main {

	public static void main(String[] args) {
		Display display = new Display();
		Shell shell = new Shell(display);
		shell.setLayout(new FillLayout());
		Browser browser = new Browser(shell, SWT.BORDER);
		browser.setUrl("https://mifritscher.de/austausch/test.html");

		shell.open();

		// run the event loop as long as the window is open
		while (!shell.isDisposed()) {
			// read the next OS event queue and transfer it to a SWT event
			if (!display.readAndDispatch()) {
				// if there are currently no other OS event to process
				// sleep until the next OS event is available
				display.sleep();
			}
		}

		// disposes all associated windows and their components
		display.dispose();
	}

}
```

**Comment by mifritscher** [comment]
After a first look, I think that it is possible to do a first shot fairly easy:

  * Stubplement ```CefDownloadHandler``` - the function onBeforeDownload() is enough.
  * This function could simply call the callback ```CefBeforeDownloadCallback.continue("", true)```.

I got the info from https://bitbucket.org/chromiumembedded/java-cef/src/master/java/org/cef/handler/CefDownloadHandler.java and https://bitbucket.org/chromiumembedded/java-cef/src/master/java/org/cef/callback/CefBeforeDownloadCallback.java. Sadly I'm not a rust programmer.

**Comment by xarezx** [comment]
Yeah it seems that the download dialog is disabled by default in cef. Is there any way to reactive it?

**Comment by lonelion** [comment]
Support for this and more features have been added in our [Equo Chromium](https://www.equoplatform.com/chromium) Enterprise offering.
