### ISSUE TITLE
Webpage is not displayed with recommended width

### ISSUE THREAD

**Issue by anup-rampoore** [equoplatform/chromium-swt#99]
I used the example provided in my View in Eclipse RCP Application. When I add a web page by providing URL, the width and height of web page is not completely filled inside a layout. To verify the same, I added background colour to Chromium 'Browser' widget. Browser widget completely occupies layouts' width and height but not the webpage.

Please have a look into this.

**Comment by gzunino** [comment]
@anup-rampoore could you share a minimal example to reproduce? Thanks
